<?php

/*
 * This file is part of Refine
 *
 * Copyright(c) 2024 Refine Co.,Ltd. All Rights Reserved.
 *
 * https://www.re-fine.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\RefineFavoriteBlock\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\RefineFavoriteBlock\Entity\RefineFavoriteBlockConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefineFavoriteBlockConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, RefineFavoriteBlockConfig::class);
    }

    /**
     * @param int $id
     * @return RefineFavoriteBlockConfig|null
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
