<?php

namespace Plugin\ApgExtendCartIn\Repository;

use Doctrine\ORM\QueryBuilder;
use Eccube\Repository\AbstractRepository;
use Plugin\ApgExtendCartIn\Entity\Config;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{

    const CACHE_KEY = "ApgExtendCartIn_Repository_ConfigRepository::getOrNew";

    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Config::class);
    }

    public function getOrNew($id = 1): ?Config
    {
        $lifetime = $this->getCacheLifetime();
        /** @var QueryBuilder $qb */
        $qb = $this->createQueryBuilder('b')
            ->where('b.id = :id')
            ->setParameter('id', $id);
        $recode = $qb->getQuery()
            ->useResultCache(true, $lifetime, self::CACHE_KEY)
            ->getOneOrNullResult();
        return empty($recode) ? new Config() : $recode;

    }

    public function save($entity)
    {
        $result = parent::save($entity);

        $em = $this->getEntityManager();
        $cacheImpl = $em->getConfiguration()->getResultCacheImpl();
        if (!empty($cacheImpl)) {
            $cacheImpl->delete(self::CACHE_KEY);
        }

        return $result;
    }
}
